from BaseClasses import Item


class SableItem(Item):
    game = "Sable"

all_items = [
    "AnAncientRaceKeyItem",
    "AtomicHeartDebtNote",
    "AtomicHeartEmptySocket",
    "AtomicHeartFeather",
    "AtomicHeartKeycard",
    "AtomicHeartPowerCoreBroken",
    "AtomicHeartPowerCoreRepaired",
    "AtomicHeartSmashedGlass",
    "AtomicHeartSuspectGaray",
    "AtomicHeartSuspectHamza",
    "AtomicHeartSuspectIria",
    "AtomicPart",
    "AtomicSuitHelmet",
    "Balloon",
    "BasicFishingRod",
    "Bolt",
    "CactusPatch",
    "CactusSpineRod",
    "Calibrator",
    "ChalkButterfly",
    "Chum",
    "ChumTear",
    "ControlPanel",
    "CrystalButterfly",
    "DuskFirefly",
    "EngineerSetHelmet",
    "EscapePodBattery",
    "FallowPomegranate",
    "Fig",
    "GlowingMushrooms",
    "Glowworm",
    "LarvalHusk",
    "LarvalHuskPackage",
    "LightningCrystal",
    "MelancholyMushroom",
    "NimoorButterflies",
    "OasisDragonfly",
    "OasisFlower",
    "OrangeWingBeetle",
    "PinkNeckEggs",
    "PowerSupply",
    "PricklyPear",
    "RustyJunk",
    "SaltButterfly",
    "ScrapMetal",
    "ShadedLeafButterfly",
    "ShyRijwurPulp",
    "SlicerBeetlePoo",
    "SmugglersHeirloom",
    "StepwellDragonfly",
    "StyllousNote",
    "SunkenTechnology",
    "SunshineButterfly",
    "TastyFish",
    "ThievingMagpiesWellDoorKey",
    "TricksterAtomicRod",
    "YellowElephantBeetle"
]

fish = [
    "ScabbyFish",
    "BellowGuppy",
    "DopeyDart",
    "PebbleEye",
    "BloatedEyeClam",
    "FlutterThrust",
    "ShelledCup",
    "Hummer",
    "SuckerFish",
    "TrifleJelly",
    "LittleKicker",
    "PillFish",
    "StormFish",
    "TeacupAngler",
    "LightKoi",
    "SandRay",
    "GhostSoul"
]
fish_clues = [
    "ScabbyFishClue",
    "BellowGuppyClue",
    "DopeyDartClue",
    "PebbleEyeClue",
    "BloatedEyeClamClue",
    "FlutterThrustClue",
    "ShelledCupClue",
    "HummerClue",
    "SuckerFishClue",
    "TrifleJellyClue",
    "LittleKickerClue",
    "PillFishClue",
    "StormFishClue",
    "TeacupAnglerClue",
    "LightKoiClue",
    "SandRayClue",
    "GhostSoulClue"
]

unused_items = [
    "SableHunchTrousers"
    "MonumentalBikeBoosterSchematic",
    "MonumentalBikeFrontSchematic",
    "MonumentalBikeWingsSchematic",
]

item_id_to_name: dict[int, str] = {
    # Badges
    4001: "AnglerBadge",
    4002: "BeetleBadge",
    4003: "CartographersBadge",
    4004: "ClimbingBadge",
    4005: "EntertainersBadge",
    4006: "GuardsBadge",
    4007: "MachinistBadge",
    4008: "MerchantBadge",
    4009: "ScrappersBadge",

    # Bike Parts
    4101: "AnglerBikeBooster",
    4102: "AnglerBikeFront",
    4103: "AnglerBikeWings",
    4104: "AtomicWhaleshipBikeBooster",
    4105: "AtomicWhaleshipBikeFront",
    4106: "AtomicWhaleshipBikeWings",
    4107: "BeetleBooster",
    4108: "BeetleFront",
    4109: "BeetleWings",
    4110: "CartoBikeBooster",
    4111: "CartoBikeFront",
    4112: "CartoBikeWings",
    4113: "DeliveryBikeBooster",
    4114: "DeliveryBikeFront",
    4115: "DeliveryBikeWings",
    4116: "DragonflyBikeBooster",
    4117: "DragonflyBikeFront",
    4118: "DragonflyBikeWings",
    4119: "EyriesBikeBooster",
    4120: "EyriesBikeFront",
    4121: "EyriesBikeWings",
    4122: "GiraffeBooster",
    4123: "GiraffeFront",
    4124: "GiraffeWings",
    4125: "GlidingBikeBooster",
    4126: "GlidingBikeFront",
    4127: "GlidingBikeWings",
    4128: "LightningCrystalBikeBooster",
    4129: "LightningCrystalBikeFront",
    4130: "LightningCrystalBikeWings",
    4131: "MonumentalRingBikeBooster",
    4132: "MonumentalRingBikeFront",
    4133: "MonumentalRingBikeWings",
    4134: "NomadicBooster",
    4135: "NomadicFront",
    4136: "NomadicWings",
    4137: "SaltBikeBooster",
    4138: "SaltBikeFront",
    4139: "SaltBikeWings",
    4140: "SandcutterBooster",
    4141: "SandcutterFront",
    4142: "SandcutterWings",
    4143: "ScrapperBikeBooster",
    4144: "ScrapperBikeFront",
    4145: "ScrapperBikeWings",
    4146: "ShadeOfEccriaBooster",
    4147: "ShadeOfEccriaFront",
    4148: "ShadeOfEccriaWings",
    4149: "SpeedsterBikeBooster",
    4150: "SpeedsterBikeFront",
    4151: "SpeedsterBikeWings",

    # Palettes
    4400: "AtomicCorePalette",
    4402: "AtomicShellPalette",
    4403: "AtomicWhaleShipBikePalette",
    4404: "AzurePalette",
    4405: "BeetleBikePalette",
    4406: "BeetleHuskPalette",
    4407: "CartographerPalette",
    4408: "CrazyBikePalette",
    4409: "DeliveryBikePalette",
    4410: "DragonFlyPalette",
    4411: "DustyMonumentPalette",
    4412: "EccrineGreenPalette",
    4413: "ExtractorPalette",
    4414: "EyriesBikePalette",
    4415: "GiraffeBikePalette",
    4416: "GlidingBikePalette",
    4417: "HakoanBlackPalette",
    4418: "IbexiiRedPalette",
    4419: "LavenderFlashPalette",
    4420: "LightningCrystalBikePalette",
    4421: "MonumentalBikePalette",
    4422: "NaturesGreenPalette",
    4423: "NeonFlashPalette",
    4424: "NomadicBikePalette",
    4425: "PyraustaGreyPalette",
    4426: "RedBikePalette",
    4427: "SaltPlainPoolsPalette",
    4428: "SandcutterBikePalette",
    4429: "SandyPalette",
    4430: "ScrapperPalette",
    4431: "SpeedsterBikePalette",
    4432: "StrawPalette",
    4433: "SunsetsPalette",
    4434: "WashBluePalette",
    4435: "WindChimePalette",

    # Masks
    4201: "AtomicPriesthoodSetMask",
    4202: "CartographersMask",
    4203: "ChildhoodSetMask",
    4204: "ChumMask",
    4205: "ClimbingSetMask",
    4206: "DeliveryMask",
    4207: "DoctorsMask",
    4208: "EntertainersMask",
    4209: "FishingSetMask",
    4210: "GuardMask",
    4211: "HerculesBeetleMask",
    4212: "HuntersMask",
    4213: "IbexiiSetMask",
    4214: "MerchantsMask",
    4215: "Monumental_Mask",
    4216: "ParasiteBeetleMask",
    4217: "SandwormMask",
    4218: "ScrappersMask",
    4219: "ShadeOfEccriaMask",
    4220: "ShepherdsMask",
    4221: "SlicerBeetleMask",


    # Clothes
    4251: "AtomicPriesthoodSetTop",
    4252: "AtomicPriesthoodSetTrousers",
    4253: "AtomicSuitTop",
    4254: "AtomicSuitTrousers",
    4255: "BeetleSetTop",
    4256: "BeetleSetTrousers",
    4257: "BikerSetTop",
    4258: "BikerSetTrousers",
    4259: "BlackDesertSetTop",
    4260: "BlackDesertSetTrousers",
    4261: "ChildhoodSetTop",
    4262: "ChildhoodSetTrousers",
    4263: "ChumTop",
    4264: "ChumBottoms",
    4265: "ClimbingSetTop",
    4266: "ClimbingSetBottoms",
    4267: "DragonFlySetTop",
    4268: "DragonFlySetTrousers",
    4269: "EccrianSetTop",
    4270: "EccrianSetTrousers",
    4271: "EngineerSetTop",
    4272: "EngineerSetTrousers",
    4273: "FingerClanSetTop",
    4274: "FingerClanSetTrousers",
    4275: "FishingSetTop",
    4276: "FishingSetTrousers",
    4277: "GuardOutfitTop",
    4278: "GuardOutfitBottoms",
    4279: "IbexiiSetTop",
    4280: "IbexiiSetTrousers",
    4281: "MonumentalTop",
    4282: "MonumentalBottom",
    4283: "ScrapperSetTop",
    4284: "ScrapperSetTrousers",
    4285: "ShadeSetTop",
    4286: "ShadeSetTrousers",
    4287: "SurferSetTop",
    4288: "SurferSetTrousers",
    4289: "WhiteDesertSetTop",
    4290: "WhiteDesertSetTrousers",

    # Maps
    4301: "BadlandsMap",
    4302: "BlackDesertMap",
    4303: "CatEarCanyonMap",
    4304: "EasternDuneMap",
    4305: "SaltPlainsMap",
    4306: "WesternDuneMap",
    4307: "WhiteDesertMap",

    # Key Items
    4351: "Compass",
    4352: "GlidingStone01",
    4353: "GlidingStone02",
    4354: "Navigator"
}

ingame_name_to_display: dict[str, str] = {
    'AnAncientRaceKeyItem': 'Hicaric Ring Artefact',
    'AnglerBadge': 'Angler Badge',
    'AnglerBikeBooster': 'Angler Bike Engine',
    'AnglerBikeFront': 'Angler Bike Front',
    'AnglerBikeWings': 'Angler Bike Wings',
    'AtomicCorePalette': 'Atomic Core Dye',
    'AtomicHeartDebtNote': 'CLUE: Promissory Note',
    'AtomicHeartEmptySocket': 'CLUE: Empty Socket',
    'AtomicHeartFeather': 'CLUE: Large Feathers',
    'AtomicHeartKeycard': 'Atomic Heart Keycard',
    'AtomicHeartPowerCoreBroken': 'Broken Atomic Heart Powercore',
    'AtomicHeartPowerCoreRepaired': 'Repaired Atomic Heart Powercore',
    'AtomicHeartSmashedGlass': 'CLUE: Smashed Glass',
    'AtomicHeartSuspectGaray': 'SUSPECT: Climber Garay',
    'AtomicHeartSuspectHamza': 'SUSPECT: Machinist Hamza',
    'AtomicHeartSuspectIria': 'SUSPECT: Merchant Iria',
    'AtomicPart': 'name',
    'AtomicPriesthoodSetMask': 'Atomic Priesthood Mask',
    'AtomicPriesthoodSetTop': 'Atomic Priesthood Torso',
    'AtomicPriesthoodSetTrousers': 'Atomic Priesthood Trousers',
    'AtomicShellPalette': 'Atomic Shell Dye',
    'AtomicSuitHelmet': 'Whale Ship Mask',
    'AtomicSuitTop': 'Whale Ship Top',
    'AtomicSuitTrousers': 'Whale Ship Trousers',
    'AtomicWhaleshipBikeBooster': 'Whale Ship Bike Engine',
    'AtomicWhaleshipBikeFront': 'Whale Ship Bike Front',
    'AtomicWhaleShipBikePalette': 'Whaleship Bike Dye',
    'AtomicWhaleshipBikeWings': 'Whale Ship Bike Wing',
    'AzurePalette': 'Azure Dye',
    'BadlandsMap': 'Badlands Map',
    'Balloon': 'name',
    'BasicFishingRod': 'Basic Wooden Rod',
    'BeetleBadge': 'Beetle Badge',
    'BeetleBikePalette': 'Beetle Bike Dye',
    'BeetleBooster': 'Beetle Bike Booster',
    'BeetleFront': 'Beetle Bike Front',
    'BeetleHuskPalette': 'Beetle Husk Dye',
    'BeetleSetTop': 'Beetle Station Top',
    'BeetleSetTrousers': 'Beetle Station Trousers',
    'BeetleWings': 'Beetle Bike Wings',
    'BellowGuppy': 'Bellow Guppy',
    'BellowGuppyClue': 'Bellow Guppy Clue',
    'BikerSetTop': 'Biker Top',
    'BikerSetTrousers': 'Bikers Trousers',
    'BlackDesertMap': 'Hakoa Map',
    'BlackDesertSetTop': 'Hakoan Top',
    'BlackDesertSetTrousers': 'Hakoan Trousers',
    'BloatedEyeClam': 'Bloated Eye Clam',
    'BloatedEyeClamClue': 'Bloated Eye Clam Clue',
    'Bolt': 'name',
    'CactusPatch': 'name',
    'CactusSpineRod': 'Cactus Spine Rod',
    'Calibrator': 'Atomic Calibrator',
    'CartoBikeBooster': 'Cartographer Bike Engine',
    'CartoBikeFront': 'Cartographer Bike Front',
    'CartoBikeWings': 'Cartographer Bike Wings',
    'CartographerPalette': 'Cartographer Bike Dye',
    'CartographersBadge': 'Cartographer\'s Badge',
    'CartographersMask': 'Cartographer\'s Mask',
    'CatEarCanyonMap': 'Ewer Map',
    'ChalkButterfly': 'Chalk Butterfly',
    'ChildhoodSetMask': 'Child\'s Mask',
    'ChildhoodSetTop': 'Ibexii Children Top',
    'ChildhoodSetTrousers': 'Ibexii Trousers',
    'Chum': 'Chum Egg',
    'ChumBottoms': 'Chum Skirt',
    'ChumMask': 'Chum Mask',
    'ChumTear': 'Chum Queen Tear',
    'ChumTop': 'Chum Top',
    'ClimbingBadge': 'Climbing Badge',
    'ClimbingSetBottoms': 'Bouldering Trousers',
    'ClimbingSetMask': 'Climbing Mask',
    'ClimbingSetTop': 'Bouldering Top',
    'Compass': 'The Compass',
    'ControlPanel': 'Atomic Control Panel',
    'CrazyBikePalette': 'Crazy Bike Dye',
    'CrystalButterfly': 'Crystal Butterfly',
    'DeliveryBikeBooster': 'Delivery Bike Engine',
    'DeliveryBikeFront': 'Delivery Bike Front',
    'DeliveryBikePalette': 'Delivery Bike Dye',
    'DeliveryBikeWings': 'Delivery Bike Wings',
    'DeliveryMask': 'name',
    'DoctorsMask': 'name',
    'DopeyDart': 'Dopey Dart',
    'DopeyDartClue': 'Dopey Dart Clue',
    'DragonflyBikeBooster': 'Dragonfly Bike Engine',
    'DragonflyBikeFront': 'Dragonfly Bike Front',
    'DragonflyBikeWings': 'Dragonfly Bike Wings',
    'DragonFlyPalette': 'Dragonfly Bike Dye',
    'DragonFlySetTop': 'Butterfly Top',
    'DragonFlySetTrousers': 'Butterfly Trousers',
    'DuskFirefly': 'Dusk Firefly',
    'DustyMonumentPalette': 'Dusty Monument Dye',
    'EasternDuneMap': 'Sansee Map',
    'EccrianSetTop': 'Eccrine Top',
    'EccrianSetTrousers': 'Eccrine Trousers',
    'EccrineGreenPalette': 'Eccrine Green Dye',
    'EngineerSetHelmet': 'Machinist\'s Mask',
    'EngineerSetTop': 'Machinist Top',
    'EngineerSetTrousers': 'Machinist Trousers',
    'EntertainersBadge': 'Entertainer\'s Badge',
    'EntertainersMask': 'Entertainer\'s Mask',
    'EscapePodBattery': 'name',
    'ExtractorPalette': 'Salt Extractor Bike Dye',
    'EyriesBikeBooster': 'Eyries Bike Booster',
    'EyriesBikeFront': 'Eyries Bike Front',
    'EyriesBikePalette': 'Eyries Bike Dye',
    'EyriesBikeWings': 'Eyries Bike Wings',
    'FallowPomegranate': 'Fallow Pomegranate ',
    'Fig': 'Narrow Stalk Fig',
    'FingerClanSetTop': 'Eyries Top',
    'FingerClanSetTrousers': 'Eyries Trousers',
    'FishingSetMask': 'Angler Mask',
    'FishingSetTop': 'Angler Top',
    'FishingSetTrousers': 'Angler Bottoms',
    'FlutterThrust': 'Flutter Thrust',
    'FlutterThrustClue': 'Flutter Thrust Clue',
    'GhostSoul': 'Ghost Soul',
    'GhostSoulClue': 'Ghost Soul Clue',
    'GiraffeBikePalette': 'Giraffe Bike Dye',
    'GiraffeBooster': 'Giraffe Bike Booster',
    'GiraffeFront': 'Giraffe Bike Front',
    'GiraffeWings': 'Giraffe Bike Wings',
    'GlidingBikeBooster': 'Gliding Bike Booster',
    'GlidingBikeFront': 'Gliding Bike Front',
    'GlidingBikePalette': 'Gliding Bike Dye',
    'GlidingBikeWings': 'Gliding Bike Wings',
    'GlidingStone01': 'Gliding Stone',
    'GlidingStone02': 'Powered Gliding Stone',
    'GlowingMushrooms': 'Glowing Mushrooms',
    'Glowworm': 'Hakoan Glowworms',
    'GuardMask': 'Guard\'s Mask',
    'GuardOutfitBottoms': 'Eccrine Guard Trousers',
    'GuardOutfitTop': 'Eccrine Guard Top',
    'GuardsBadge': 'Guard\'s Badge',
    'HakoanBlackPalette': 'Hakoan Black Dye',
    'HerculesBeetleMask': 'Hercules Beetle Mask',
    'Hummer': 'Hummer',
    'HummerClue': 'Hummer Clue',
    'HuntersMask': 'Hunters Mask',
    'IbexiiRedPalette': 'Ibexii Red Dye',
    'IbexiiSetMask': 'Ibexii Mask',
    'IbexiiSetTop': 'Ibexii Glider Top',
    'IbexiiSetTrousers': 'Ibexii Glider Trousers',
    'LarvalHusk': 'Hercules Beetle Larvae Husk',
    'LarvalHuskPackage': 'Larval Husk Package',
    'LavenderFlashPalette': 'Lavender Flash Dye',
    'LightKoi': 'Light Koi',
    'LightKoiClue': 'Light Koi Clue',
    'LightningCrystal': 'Lightning Crystal',
    'LightningCrystalBikeBooster': 'Lightning Crystal Bike Booster',
    'LightningCrystalBikeFront': 'Lightning Crystal Bike Front',
    'LightningCrystalBikePalette': 'Lightning Crystal Bike Dye',
    'LightningCrystalBikeWings': 'Lightning Crystal Bike Wings',
    'LittleKicker': 'Little Kicker',
    'LittleKickerClue': 'Little Kicker Clue',
    'MachinistBadge': 'Machinist Badge',
    'MelancholyMushroom': 'Melancholy Mushroom',
    'MerchantBadge': 'Merchant Badge',
    'MerchantsMask': 'Merchant\'s Mask',
    'Monumental_Mask': 'name',
    'MonumentalBikeBoosterSchematic': 'Hicaric Bike Booster Schematic',
    'MonumentalBikeFrontSchematic': 'Hicaric Bike Front Schematic',
    'MonumentalBikePalette': 'Monumental Bike Dye',
    'MonumentalBikeWingsSchematic': 'Hicaric Bike Wings Schematic',
    'MonumentalBottom': 'Monumental Stone Bottoms',
    'MonumentalRingBikeBooster': 'Hicaric Ring Bike Booster',
    'MonumentalRingBikeFront': 'Hicaric Ring Bike Front',
    'MonumentalRingBikeWings': 'Hicaric Ring Bike Wings',
    'MonumentalTop': 'Monumental Stone Top',
    'NaturesGreenPalette': 'Natures Green Dye',
    'Navigator': 'The Navigator',
    'NeonFlashPalette': 'Neon Flash Dye',
    'NimoorButterflies': 'Nimoor Butterflies',
    'NomadicBikePalette': 'Nomadic Bike Dye',
    'NomadicBooster': 'Nomadic Bike Engine',
    'NomadicFront': 'Nomadic Bike Front',
    'NomadicWings': 'Nomadic Bike Wing',
    'OasisDragonfly': 'Oasis Dragonfly',
    'OasisFlower': 'Oasis Flower',
    'OrangeWingBeetle': 'Orange Winged Beetles',
    'ParasiteBeetleMask': 'Oranged Ringed Beetle Mask',
    'PebbleEye': 'Pebble Eye',
    'PebbleEyeClue': 'Pebble Eye Clue',
    'PillFish': 'Pill Fish',
    'PillFishClue': 'Pill Fish Clue',
    'PinkNeckEggs': 'Pink Neck Eggs',
    'PowerSupply': 'Atomic Power Supply',
    'PricklyPear': 'Prickly Pear',
    'PyraustaGreyPalette': 'Pyrausta Grey Dye',
    'RedBikePalette': 'Red Bike Dye',
    'RustyJunk': 'name',
    'SableHunchTrousers': 'Sable Hunch Trousers',
    'SaltBikeBooster': 'Salt Bike Engine',
    'SaltBikeFront': 'Salt Bike Front',
    'SaltBikeWings': 'Salt Bike Wings',
    'SaltButterfly': 'Salt Butterfly',
    'SaltPlainPoolsPalette': 'Salt Plain Pools Dye',
    'SaltPlainsMap': 'Sodic Waste Map',
    'SandcutterBikePalette': 'Sandcutter Bike Dye',
    'SandcutterBooster': 'Sandcutter Engine',
    'SandcutterFront': 'Sandcutter Front',
    'SandcutterWings': 'Sandcutter Wings',
    'SandRay': 'Sand Ray',
    'SandRayClue': 'Sand Ray Clue',
    'SandwormMask': 'Sandwyrm Mask',
    'SandyPalette': 'Sandy Dye',
    'ScabbyFish': 'Scabby Fish',
    'ScabbyFishClue': 'Scabby Fish Clue',
    'ScrapMetal': 'Scrap Metal',
    'ScrapperBikeBooster': 'Scrapper Bike Engine',
    'ScrapperBikeFront': 'Scrapper Bike Front',
    'ScrapperBikeWings': 'Scrapper Bike Wings',
    'ScrapperPalette': 'Scrapper Bike Dye',
    'ScrappersBadge': 'Scrapper\'s Badge',
    'ScrapperSetTop': 'Scrapper Top',
    'ScrapperSetTrousers': 'Scrapper Bottoms',
    'ScrappersMask': 'Scrapper Mask',
    'ShadedLeafButterfly': 'Shaded Leaf Butterfly',
    'ShadeOfEccriaBooster': 'Shade Bike Booster',
    'ShadeOfEccriaFront': 'Shade Bike Front',
    'ShadeOfEccriaMask': 'Shade of Eccria Mask',
    'ShadeOfEccriaWings': 'Shade Bike Wings',
    'ShadeSetTop': 'Shade Top',
    'ShadeSetTrousers': 'Shade Trousers',
    'ShelledCup': 'Shelled Cup',
    'ShelledCupClue': 'Shelled Cup Clue',
    'ShepherdsMask': 'Shepherd Mask',
    'ShyRijwurPulp': 'Shy Rijwur Pulp',
    'SlicerBeetleMask': 'Slicer Beetle Mask',
    'SlicerBeetlePoo': 'Slicer Beetle Poo',
    'SmugglersHeirloom': 'name',
    'SpeedsterBikeBooster': 'Speedster Bike Engine',
    'SpeedsterBikeFront': 'Speedster Bike Front',
    'SpeedsterBikePalette': 'Speedster Bike Dye',
    'SpeedsterBikeWings': 'Speedster Bike Wing',
    'StepwellDragonfly': 'Stepwell Dragonfly',
    'StormFish': 'Storm Fish',
    'StormFishClue': 'Storm Fish Clue',
    'StrawPalette': 'Straw Dye',
    'StyllousNote': 'Mysterious Note',
    'SuckerFish': 'Sucker Fish',
    'SuckerFishClue': 'Sucker Fish Clue',
    'SunkenTechnology': 'name',
    'SunsetsPalette': 'Sunsets Dye',
    'SunshineButterfly': 'Sunshine Butterfly',
    'SurferSetTop': 'Sand Surfer Top',
    'SurferSetTrousers': 'Sand Surfer Shorts',
    'TastyFish': 'name',
    'TeacupAngler': 'Teacup Angler',
    'TeacupAnglerClue': 'Teacup Angler Clue',
    'ThievingMagpiesWellDoorKey': 'Magpie Key',
    'TricksterAtomicRod': 'Trickster Atomic Rod',
    'TrifleJelly': 'Trifle Jelly',
    'TrifleJellyClue': 'Trifle Jelly Clue',
    'WashBluePalette': 'Wash Blue Dye',
    'WesternDuneMap': 'Redsee Map',
    'WhiteDesertMap': 'The Wash Map',
    'WhiteDesertSetTop': 'Wash Top',
    'WhiteDesertSetTrousers': 'Wash Trousers',
    'WindChimePalette': 'Wind Chime Dye',
    'YellowElephantBeetle': 'Yellow Elephant Beetle'
}

if __name__ == "__main__":
    print("\""+"\", \n\"".join(filter(lambda x: x not in item_id_to_name.values(), all_items))+"\"")