import random
from typing import TypeVar, Any

from BaseClasses import Item, ItemClassification


class SableItem(Item):
    game = "Sable"

# Non Randomized Items #
unused_items = [
    "SableHunchTrousers"
    "MonumentalBikeBoosterSchematic",
    "MonumentalBikeFrontSchematic",
    "MonumentalBikeWingsSchematic",
    "AtomicPart",
    "AtomicPriesthoodSetMask",
    "DeliveryMask",
    "DoctorsMask",
    "HuntersMask",
    "Monumental_Mask",
    "ParasiteBeetleMask",
    "ShepherdsMask",
    "SlicerBeetleMask",
    "Balloon",
    "Bolt",
    "CactusPatch",
    "CactusSpineRod", # Could be in the game, but I don't know what this is
    "EscapePodBattery",
    "RustyJunk",
    "SmugglersHeirloom",
    "SunkenTechnology",
    "TastyFish",
    "StyllousNote", # Could be in the game, but I don't know what this is
]

game_starting_items = [
    "ChildhoodSetMask",
    "ChildhoodSetTop",
    "ChildhoodSetTrousers",
]

prologue_items = [
    "Calibrator",
    "ControlPanel",
    "PowerSupply",
]

# Randomized Items #
# Keep Id's 4800-5000 free for Locations of duplicate items (Locations take the same id's as the items)

random_shit = { # Some of these are quest items, but generally unimportant
    4701: "FallowPomegranate",
    4702: "Fig",
    4703: "GlowingMushrooms",
    4704: "LarvalHusk",
    4705: "LarvalHuskPackage",
    4706: "LightningCrystal",
    4707: "MelancholyMushroom",
    4708: "OasisFlower",
    4709: "PinkNeckEggs",
    4710: "PricklyPear",
    4711: "ScrapMetal",
    4712: "ShyRijwurPulp",
    4713: "SlicerBeetlePoo",
    4714: "ThievingMagpiesWellDoorKey",
}
insects = {
    4721: "ChalkButterfly",
    4722: "CrystalButterfly",
    4723: "DuskFirefly",
    4724: "Glowworm",
    4725: "NimoorButterflies",
    4726: "OasisDragonfly",
    4727: "OrangeWingBeetle",
    4728: "SaltButterfly",
    4729: "ShadedLeafButterfly",
    4730: "StepwellDragonfly",
    4731: "SunshineButterfly",
    4732: "YellowElephantBeetle"
}
fish = {
    4741: "ScabbyFish",
    4742: "BellowGuppy",
    4743: "DopeyDart",
    4744: "PebbleEye",
    4745: "BloatedEyeClam",
    4746: "FlutterThrust",
    4747: "ShelledCup",
    4748: "Hummer",
    4749: "SuckerFish",
    4750: "TrifleJelly",
    4751: "LittleKicker",
    4752: "PillFish",
    4753: "StormFish",
    4754: "TeacupAngler",
    4755: "LightKoi",
    4756: "SandRay",
    4757: "GhostSoul"
}
atomic_heart_clues = {
    4761: "AtomicHeartDebtNote",  # 'CLUE: Promissory Note',
    4762: "AtomicHeartEmptySocket",  # 'CLUE: Empty Socket',
    4763: "AtomicHeartFeather",  # 'CLUE: Large Feathers',
    4764: "AtomicHeartSmashedGlass",  # 'CLUE: Smashed Glass',
    4765: "AtomicHeartSuspectGaray",  # 'SUSPECT: Climber Garay',
    4766: "AtomicHeartSuspectHamza",  # 'SUSPECT: Machinist Hamza',
    4767: "AtomicHeartSuspectIria",  # 'SUSPECT: Merchant Iria',
}
fish_clues = {
    4771: "ScabbyFishClue",
    4772: "BellowGuppyClue",
    4773: "DopeyDartClue",
    4774: "PebbleEyeClue",
    4775: "BloatedEyeClamClue",
    4776: "FlutterThrustClue",
    4777: "ShelledCupClue",
    4778: "HummerClue",
    4779: "SuckerFishClue",
    4780: "TrifleJellyClue",
    4781: "LittleKickerClue",
    4782: "PillFishClue",
    4783: "StormFishClue",
    4784: "TeacupAnglerClue",
    4785: "LightKoiClue",
    4786: "SandRayClue",
    4787: "GhostSoulClue"
}



bike_parts = {
    # Bike Parts
    # Reserved Id's: 4101-4199
    4101: "AnglerBikeBooster",
    4102: "AnglerBikeFront",
    4103: "AnglerBikeWings",
    4104: "AtomicWhaleshipBikeBooster",
    4105: "AtomicWhaleshipBikeFront",
    4106: "AtomicWhaleshipBikeWings",
    4107: "BeetleBooster",
    4108: "BeetleFront",
    4109: "BeetleWings",
    4110: "CartoBikeBooster",
    4111: "CartoBikeFront",
    4112: "CartoBikeWings",
    4113: "DeliveryBikeBooster",
    4114: "DeliveryBikeFront",
    4115: "DeliveryBikeWings",
    4116: "DragonflyBikeBooster",
    4117: "DragonflyBikeFront",
    4118: "DragonflyBikeWings",
    4119: "EyriesBikeBooster",
    4120: "EyriesBikeFront",
    4121: "EyriesBikeWings",
    4122: "GiraffeBooster",
    4123: "GiraffeFront",
    4124: "GiraffeWings",
    4125: "GlidingBikeBooster",
    4126: "GlidingBikeFront",
    4127: "GlidingBikeWings",
    4128: "LightningCrystalBikeBooster",
    4129: "LightningCrystalBikeFront",
    4130: "LightningCrystalBikeWings",
    4131: "MonumentalRingBikeBooster",
    4132: "MonumentalRingBikeFront",
    4133: "MonumentalRingBikeWings",
    4134: "NomadicBooster",
    4135: "NomadicFront",
    4136: "NomadicWings",
    4137: "SaltBikeBooster",
    4138: "SaltBikeFront",
    4139: "SaltBikeWings",
    4140: "SandcutterBooster",
    4141: "SandcutterFront",
    4142: "SandcutterWings",
    4143: "ScrapperBikeBooster",
    4144: "ScrapperBikeFront",
    4145: "ScrapperBikeWings",
    4146: "ShadeOfEccriaBooster",
    4147: "ShadeOfEccriaFront",
    4148: "ShadeOfEccriaWings",
    4149: "SpeedsterBikeBooster",
    4150: "SpeedsterBikeFront",
    4151: "SpeedsterBikeWings",
}

bike_palettes = {
    # Palettes
    # Reserved Id's: 4401-4499
    4401: "AtomicCorePalette",
    4402: "AtomicShellPalette",
    4403: "AtomicWhaleShipBikePalette",
    4404: "AzurePalette",
    4405: "BeetleBikePalette",
    4406: "BeetleHuskPalette",
    4407: "CartographerPalette",
    4408: "CrazyBikePalette",
    4409: "DeliveryBikePalette",
    4410: "DragonFlyPalette",
    4411: "DustyMonumentPalette",
    4412: "EccrineGreenPalette",
    4413: "ExtractorPalette",
    4414: "EyriesBikePalette",
    4415: "GiraffeBikePalette",
    4416: "GlidingBikePalette",
    4417: "HakoanBlackPalette",
    4418: "IbexiiRedPalette",
    4419: "LavenderFlashPalette",
    4420: "LightningCrystalBikePalette",
    4421: "MonumentalBikePalette",
    4422: "NaturesGreenPalette",
    4423: "NeonFlashPalette",
    4424: "NomadicBikePalette",
    4425: "PyraustaGreyPalette",
    4426: "RedBikePalette",
    4427: "SaltPlainPoolsPalette",
    4428: "SandcutterBikePalette",
    4429: "SandyPalette",
    4430: "ScrapperPalette",
    4431: "SpeedsterBikePalette",
    4432: "StrawPalette",
    4433: "SunsetsPalette",
    4434: "WashBluePalette",
    4435: "WindChimePalette",
}

clothes = {
    # Clothes
    # Reserved Id's: 4251-4299
    4251: "AtomicPriesthoodSetTop",
    4252: "AtomicPriesthoodSetTrousers",
    4253: "AtomicSuitTop",
    4254: "AtomicSuitTrousers",
    4255: "BeetleSetTop",
    4256: "BeetleSetTrousers",
    4257: "BikerSetTop",
    4258: "BikerSetTrousers",
    4259: "BlackDesertSetTop",
    4260: "BlackDesertSetTrousers",
    4261: "ChumTop",
    4262: "ChumBottoms",
    4263: "ClimbingSetTop",
    4264: "ClimbingSetBottoms",
    4265: "DragonFlySetTop",
    4266: "DragonFlySetTrousers",
    4267: "EccrianSetTop",
    4268: "EccrianSetTrousers",
    4269: "EngineerSetTop",
    4270: "EngineerSetTrousers",
    4271: "FingerClanSetTop",
    4272: "FingerClanSetTrousers",
    4273: "FishingSetTop",
    4274: "FishingSetTrousers",
    4275: "GuardOutfitTop",
    4276: "GuardOutfitBottoms",
    4277: "IbexiiSetTop",
    4278: "IbexiiSetTrousers",
    4279: "MonumentalTop",
    4280: "MonumentalBottom",
    4281: "ScrapperSetTop",
    4282: "ScrapperSetTrousers",
    4283: "ShadeSetTop",
    4284: "ShadeSetTrousers",
    4285: "SurferSetTop",
    4286: "SurferSetTrousers",
    4287: "WhiteDesertSetTop",
    4288: "WhiteDesertSetTrousers",
}

badges = {
    # Badges
    # Reserved Id's: 4001-4049
    4001: "AnglerBadge",
    4002: "BeetleBadge",
    4003: "CartographersBadge",
    4004: "ClimbingBadge",
    4005: "EntertainersBadge",
    4006: "GuardsBadge",
    4007: "MachinistBadge",
    4008: "MerchantBadge",
    4009: "ScrappersBadge",
}

masks = {
    # Masks
    # Reserved Id's: 4201-4249
    4201: "AtomicSuitHelmet",
    4202: "CartographersMask",
    4203: "ChumMask",
    4204: "ClimbingSetMask",
    4205: "EngineerSetHelmet",
    4206: "EntertainersMask",
    4207: "FishingSetMask",
    4208: "GuardMask",
    4209: "HerculesBeetleMask",
    4210: "IbexiiSetMask",
    4211: "MerchantsMask",
    4212: "SandwormMask",
    4213: "ScrappersMask",
    4214: "ShadeOfEccriaMask",
}

maps = {
    # Maps
    # Reserved Id's: 4301-4349
    4301: "BadlandsMap",
    4302: "BlackDesertMap",
    4303: "CatEarCanyonMap",
    4304: "EasternDuneMap",
    4305: "SaltPlainsMap",
    4306: "WesternDuneMap",
    4307: "WhiteDesertMap",
}

key_items = {
    # Key Items
    # Reserved Id's: 4351-4399
    4351: "Compass",
    4352: "GlidingStone01",
    4353: "GlidingStone02",
    4354: "Navigator",
    4355: "AnAncientRaceKeyItem",  # There should be 6 in the pool
    4356: "BasicFishingRod",
    4357: "TricksterAtomicRod",
    4358: "Chum",  # There should be 165 in the pool
    4359: "ChumTear",  # There should be 6 in the pool

    # Atomic Heart Quest Items,
    4360: "AtomicHeartKeycard",  # 'Atomic Heart Keycard',
    4361: "AtomicHeartPowerCoreBroken",  # 'Broken Atomic Heart Powercore',
    4362: "AtomicHeartPowerCoreRepaired",  # 'Repaired Atomic Heart Powercore',
}

def get_classification(item_id: int) -> ItemClassification:
    if item_id in key_items | badges:
        return ItemClassification.progression
    if item_id in maps | bike_parts:
        return ItemClassification.useful
    return ItemClassification.filler

T = TypeVar("T")
K = TypeVar("K")
L = TypeVar("L")
def transitive_dict(dict1: dict[K, T], dict2: dict[T, L]) -> dict[K, L]:
    return {k: dict2[v] for k, v in dict1.items()}
ingame_name_to_display: dict[str, str] = {
    'AnAncientRaceKeyItem': 'Hicaric Ring Artefact',
    'AnglerBadge': 'Angler Badge',
    'AnglerBikeBooster': 'Angler Bike Engine',
    'AnglerBikeFront': 'Angler Bike Front',
    'AnglerBikeWings': 'Angler Bike Wings',
    'AtomicCorePalette': 'Atomic Core Dye',
    'AtomicHeartKeycard':'Atomic Heart Keycard',
    'AtomicHeartPowerCoreBroken':'Broken Atomic Heart Powercore',
    'AtomicHeartPowerCoreRepaired':'Repaired Atomic Heart Powercore',
    'AtomicHeartDebtNote': 'CLUE: Promissory Note',
    'AtomicHeartEmptySocket': 'CLUE: Empty Socket',
    'AtomicHeartFeather': 'CLUE: Large Feathers',
    'AtomicHeartSmashedGlass': 'CLUE: Smashed Glass',
    'AtomicHeartSuspectGaray': 'SUSPECT: Climber Garay',
    'AtomicHeartSuspectHamza': 'SUSPECT: Machinist Hamza',
    'AtomicHeartSuspectIria': 'SUSPECT: Merchant Iria',
    'AtomicPart': 'name',
    'AtomicPriesthoodSetMask': 'Atomic Priesthood Mask',
    'AtomicPriesthoodSetTop': 'Atomic Priesthood Torso',
    'AtomicPriesthoodSetTrousers': 'Atomic Priesthood Trousers',
    'AtomicShellPalette': 'Atomic Shell Dye',
    'AtomicSuitHelmet': 'Whale Ship Mask',
    'AtomicSuitTop': 'Whale Ship Top',
    'AtomicSuitTrousers': 'Whale Ship Trousers',
    'AtomicWhaleshipBikeBooster': 'Whale Ship Bike Engine',
    'AtomicWhaleshipBikeFront': 'Whale Ship Bike Front',
    'AtomicWhaleShipBikePalette': 'Whaleship Bike Dye',
    'AtomicWhaleshipBikeWings': 'Whale Ship Bike Wing',
    'AzurePalette': 'Azure Dye',
    'BadlandsMap': 'Badlands Map',
    'Balloon': 'name',
    'BasicFishingRod': 'Basic Wooden Rod',
    'BeetleBadge': 'Beetle Badge',
    'BeetleBikePalette': 'Beetle Bike Dye',
    'BeetleBooster': 'Beetle Bike Booster',
    'BeetleFront': 'Beetle Bike Front',
    'BeetleHuskPalette': 'Beetle Husk Dye',
    'BeetleSetTop': 'Beetle Station Top',
    'BeetleSetTrousers': 'Beetle Station Trousers',
    'BeetleWings': 'Beetle Bike Wings',
    'BellowGuppy': 'Bellow Guppy',
    'BellowGuppyClue': 'Bellow Guppy Clue',
    'BikerSetTop': 'Biker Top',
    'BikerSetTrousers': 'Bikers Trousers',
    'BlackDesertMap': 'Hakoa Map',
    'BlackDesertSetTop': 'Hakoan Top',
    'BlackDesertSetTrousers': 'Hakoan Trousers',
    'BloatedEyeClam': 'Bloated Eye Clam',
    'BloatedEyeClamClue': 'Bloated Eye Clam Clue',
    'Bolt': 'name',
    'CactusPatch': 'name',
    'CactusSpineRod': 'Cactus Spine Rod',
    'Calibrator': 'Atomic Calibrator',
    'CartoBikeBooster': 'Cartographer Bike Engine',
    'CartoBikeFront': 'Cartographer Bike Front',
    'CartoBikeWings': 'Cartographer Bike Wings',
    'CartographerPalette': 'Cartographer Bike Dye',
    'CartographersBadge': 'Cartographer\'s Badge',
    'CartographersMask': 'Cartographer\'s Mask',
    'CatEarCanyonMap': 'Ewer Map',
    'ChalkButterfly': 'Chalk Butterfly',
    'ChildhoodSetMask': 'Child\'s Mask',
    'ChildhoodSetTop': 'Ibexii Children Top',
    'ChildhoodSetTrousers': 'Ibexii Trousers',
    'Chum': 'Chum Egg',
    'ChumBottoms': 'Chum Skirt',
    'ChumMask': 'Chum Mask',
    'ChumTear': 'Chum Queen Tear',
    'ChumTop': 'Chum Top',
    'ClimbingBadge': 'Climbing Badge',
    'ClimbingSetBottoms': 'Bouldering Trousers',
    'ClimbingSetMask': 'Climbing Mask',
    'ClimbingSetTop': 'Bouldering Top',
    'Compass': 'The Compass',
    'ControlPanel': 'Atomic Control Panel',
    'CrazyBikePalette': 'Crazy Bike Dye',
    'CrystalButterfly': 'Crystal Butterfly',
    'DeliveryBikeBooster': 'Delivery Bike Engine',
    'DeliveryBikeFront': 'Delivery Bike Front',
    'DeliveryBikePalette': 'Delivery Bike Dye',
    'DeliveryBikeWings': 'Delivery Bike Wings',
    'DeliveryMask': 'name',
    'DoctorsMask': 'name',
    'DopeyDart': 'Dopey Dart',
    'DopeyDartClue': 'Dopey Dart Clue',
    'DragonflyBikeBooster': 'Dragonfly Bike Engine',
    'DragonflyBikeFront': 'Dragonfly Bike Front',
    'DragonflyBikeWings': 'Dragonfly Bike Wings',
    'DragonFlyPalette': 'Dragonfly Bike Dye',
    'DragonFlySetTop': 'Butterfly Top',
    'DragonFlySetTrousers': 'Butterfly Trousers',
    'DuskFirefly': 'Dusk Firefly',
    'DustyMonumentPalette': 'Dusty Monument Dye',
    'EasternDuneMap': 'Sansee Map',
    'EccrianSetTop': 'Eccrine Top',
    'EccrianSetTrousers': 'Eccrine Trousers',
    'EccrineGreenPalette': 'Eccrine Green Dye',
    'EngineerSetHelmet': 'Machinist\'s Mask',
    'EngineerSetTop': 'Machinist Top',
    'EngineerSetTrousers': 'Machinist Trousers',
    'EntertainersBadge': 'Entertainer\'s Badge',
    'EntertainersMask': 'Entertainer\'s Mask',
    'EscapePodBattery': 'name',
    'ExtractorPalette': 'Salt Extractor Bike Dye',
    'EyriesBikeBooster': 'Eyries Bike Booster',
    'EyriesBikeFront': 'Eyries Bike Front',
    'EyriesBikePalette': 'Eyries Bike Dye',
    'EyriesBikeWings': 'Eyries Bike Wings',
    'FallowPomegranate': 'Fallow Pomegranate ',
    'Fig': 'Narrow Stalk Fig',
    'FingerClanSetTop': 'Eyries Top',
    'FingerClanSetTrousers': 'Eyries Trousers',
    'FishingSetMask': 'Angler Mask',
    'FishingSetTop': 'Angler Top',
    'FishingSetTrousers': 'Angler Bottoms',
    'FlutterThrust': 'Flutter Thrust',
    'FlutterThrustClue': 'Flutter Thrust Clue',
    'GhostSoul': 'Ghost Soul',
    'GhostSoulClue': 'Ghost Soul Clue',
    'GiraffeBikePalette': 'Giraffe Bike Dye',
    'GiraffeBooster': 'Giraffe Bike Booster',
    'GiraffeFront': 'Giraffe Bike Front',
    'GiraffeWings': 'Giraffe Bike Wings',
    'GlidingBikeBooster': 'Gliding Bike Booster',
    'GlidingBikeFront': 'Gliding Bike Front',
    'GlidingBikePalette': 'Gliding Bike Dye',
    'GlidingBikeWings': 'Gliding Bike Wings',
    'GlidingStone01': 'Gliding Stone',
    'GlidingStone02': 'Powered Gliding Stone',
    'GlowingMushrooms': 'Glowing Mushrooms',
    'Glowworm': 'Hakoan Glowworms',
    'GuardMask': 'Guard\'s Mask',
    'GuardOutfitBottoms': 'Eccrine Guard Trousers',
    'GuardOutfitTop': 'Eccrine Guard Top',
    'GuardsBadge': 'Guard\'s Badge',
    'HakoanBlackPalette': 'Hakoan Black Dye',
    'HerculesBeetleMask': 'Hercules Beetle Mask',
    'Hummer': 'Hummer',
    'HummerClue': 'Hummer Clue',
    'HuntersMask': 'Hunters Mask',
    'IbexiiRedPalette': 'Ibexii Red Dye',
    'IbexiiSetMask': 'Ibexii Mask',
    'IbexiiSetTop': 'Ibexii Glider Top',
    'IbexiiSetTrousers': 'Ibexii Glider Trousers',
    'LarvalHusk': 'Hercules Beetle Larvae Husk',
    'LarvalHuskPackage': 'Larval Husk Package',
    'LavenderFlashPalette': 'Lavender Flash Dye',
    'LightKoi': 'Light Koi',
    'LightKoiClue': 'Light Koi Clue',
    'LightningCrystal': 'Lightning Crystal',
    'LightningCrystalBikeBooster': 'Lightning Crystal Bike Booster',
    'LightningCrystalBikeFront': 'Lightning Crystal Bike Front',
    'LightningCrystalBikePalette': 'Lightning Crystal Bike Dye',
    'LightningCrystalBikeWings': 'Lightning Crystal Bike Wings',
    'LittleKicker': 'Little Kicker',
    'LittleKickerClue': 'Little Kicker Clue',
    'MachinistBadge': 'Machinist Badge',
    'MelancholyMushroom': 'Melancholy Mushroom',
    'MerchantBadge': 'Merchant Badge',
    'MerchantsMask': 'Merchant\'s Mask',
    'Monumental_Mask': 'name',
    'MonumentalBikeBoosterSchematic': 'Hicaric Bike Booster Schematic',
    'MonumentalBikeFrontSchematic': 'Hicaric Bike Front Schematic',
    'MonumentalBikePalette': 'Monumental Bike Dye',
    'MonumentalBikeWingsSchematic': 'Hicaric Bike Wings Schematic',
    'MonumentalBottom': 'Monumental Stone Bottoms',
    'MonumentalRingBikeBooster': 'Hicaric Ring Bike Booster',
    'MonumentalRingBikeFront': 'Hicaric Ring Bike Front',
    'MonumentalRingBikeWings': 'Hicaric Ring Bike Wings',
    'MonumentalTop': 'Monumental Stone Top',
    'NaturesGreenPalette': 'Natures Green Dye',
    'Navigator': 'The Navigator',
    'NeonFlashPalette': 'Neon Flash Dye',
    'NimoorButterflies': 'Nimoor Butterflies',
    'NomadicBikePalette': 'Nomadic Bike Dye',
    'NomadicBooster': 'Nomadic Bike Engine',
    'NomadicFront': 'Nomadic Bike Front',
    'NomadicWings': 'Nomadic Bike Wing',
    'OasisDragonfly': 'Oasis Dragonfly',
    'OasisFlower': 'Oasis Flower',
    'OrangeWingBeetle': 'Orange Winged Beetles',
    'ParasiteBeetleMask': 'Oranged Ringed Beetle Mask',
    'PebbleEye': 'Pebble Eye',
    'PebbleEyeClue': 'Pebble Eye Clue',
    'PillFish': 'Pill Fish',
    'PillFishClue': 'Pill Fish Clue',
    'PinkNeckEggs': 'Pink Neck Eggs',
    'PowerSupply': 'Atomic Power Supply',
    'PricklyPear': 'Prickly Pear',
    'PyraustaGreyPalette': 'Pyrausta Grey Dye',
    'RedBikePalette': 'Red Bike Dye',
    'RustyJunk': 'name',
    'SableHunchTrousers': 'Sable Hunch Trousers',
    'SaltBikeBooster': 'Salt Bike Engine',
    'SaltBikeFront': 'Salt Bike Front',
    'SaltBikeWings': 'Salt Bike Wings',
    'SaltButterfly': 'Salt Butterfly',
    'SaltPlainPoolsPalette': 'Salt Plain Pools Dye',
    'SaltPlainsMap': 'Sodic Waste Map',
    'SandcutterBikePalette': 'Sandcutter Bike Dye',
    'SandcutterBooster': 'Sandcutter Engine',
    'SandcutterFront': 'Sandcutter Front',
    'SandcutterWings': 'Sandcutter Wings',
    'SandRay': 'Sand Ray',
    'SandRayClue': 'Sand Ray Clue',
    'SandwormMask': 'Sandwyrm Mask',
    'SandyPalette': 'Sandy Dye',
    'ScabbyFish': 'Scabby Fish',
    'ScabbyFishClue': 'Scabby Fish Clue',
    'ScrapMetal': 'Scrap Metal',
    'ScrapperBikeBooster': 'Scrapper Bike Engine',
    'ScrapperBikeFront': 'Scrapper Bike Front',
    'ScrapperBikeWings': 'Scrapper Bike Wings',
    'ScrapperPalette': 'Scrapper Bike Dye',
    'ScrappersBadge': 'Scrapper\'s Badge',
    'ScrapperSetTop': 'Scrapper Top',
    'ScrapperSetTrousers': 'Scrapper Bottoms',
    'ScrappersMask': 'Scrapper Mask',
    'ShadedLeafButterfly': 'Shaded Leaf Butterfly',
    'ShadeOfEccriaBooster': 'Shade Bike Booster',
    'ShadeOfEccriaFront': 'Shade Bike Front',
    'ShadeOfEccriaMask': 'Shade of Eccria Mask',
    'ShadeOfEccriaWings': 'Shade Bike Wings',
    'ShadeSetTop': 'Shade Top',
    'ShadeSetTrousers': 'Shade Trousers',
    'ShelledCup': 'Shelled Cup',
    'ShelledCupClue': 'Shelled Cup Clue',
    'ShepherdsMask': 'Shepherd Mask',
    'ShyRijwurPulp': 'Shy Rijwur Pulp',
    'SlicerBeetleMask': 'Slicer Beetle Mask',
    'SlicerBeetlePoo': 'Slicer Beetle Poo',
    'SmugglersHeirloom': 'name',
    'SpeedsterBikeBooster': 'Speedster Bike Engine',
    'SpeedsterBikeFront': 'Speedster Bike Front',
    'SpeedsterBikePalette': 'Speedster Bike Dye',
    'SpeedsterBikeWings': 'Speedster Bike Wing',
    'StepwellDragonfly': 'Stepwell Dragonfly',
    'StormFish': 'Storm Fish',
    'StormFishClue': 'Storm Fish Clue',
    'StrawPalette': 'Straw Dye',
    'StyllousNote': 'Mysterious Note',
    'SuckerFish': 'Sucker Fish',
    'SuckerFishClue': 'Sucker Fish Clue',
    'SunkenTechnology': 'name',
    'SunsetsPalette': 'Sunsets Dye',
    'SunshineButterfly': 'Sunshine Butterfly',
    'SurferSetTop': 'Sand Surfer Top',
    'SurferSetTrousers': 'Sand Surfer Shorts',
    'TastyFish': 'name',
    'TeacupAngler': 'Teacup Angler',
    'TeacupAnglerClue': 'Teacup Angler Clue',
    'ThievingMagpiesWellDoorKey': 'Magpie Key',
    'TricksterAtomicRod': 'Trickster Atomic Rod',
    'TrifleJelly': 'Trifle Jelly',
    'TrifleJellyClue': 'Trifle Jelly Clue',
    'WashBluePalette': 'Wash Blue Dye',
    'WesternDuneMap': 'Redsee Map',
    'WhiteDesertMap': 'The Wash Map',
    'WhiteDesertSetTop': 'Wash Top',
    'WhiteDesertSetTrousers': 'Wash Trousers',
    'WindChimePalette': 'Wind Chime Dye',
    'YellowElephantBeetle': 'Yellow Elephant Beetle'
}

filler = random_shit | insects | fish # Filler items can be collected multiple times
item_id_to_name: dict[int, str] = transitive_dict(key_items | maps | badges | clothes | bike_palettes | bike_parts | filler| atomic_heart_clues | fish_clues, ingame_name_to_display)

item_name_to_id: dict[str, int] = {v: k for k, v in item_id_to_name.items()}

item_name_groups = {
    "masks": set([v for k, v in transitive_dict(masks, ingame_name_to_display).items()]),
    "badges": set([v for k, v in transitive_dict(badges, ingame_name_to_display).items()]),
    "bike_parts": set([v for k, v in transitive_dict(bike_parts, ingame_name_to_display).items()]),
    "maps": set([v for k, v in transitive_dict(maps, ingame_name_to_display).items()]),
}

filler_names = {v for _, v in transitive_dict(filler, ingame_name_to_display).items()}

def get_random_filler() -> str:
    id = random.choice(list(filler.keys()))
    return item_id_to_name[id]


