<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>com.thegamefire.sablearchipelago</AssemblyName>
    <Product>SableArchipelago</Product>
    <Version>1.0.0</Version>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>com.thegamefire.sablearchipelago</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Archipelago.MultiClient.Net" Version="6.7.0" >
      <Private>true</Private>
      <CopyLocal>true</CopyLocal>
    </PackageReference>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.*" IncludeAssets="compile" />
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\Sable\BepInEx\interop\Assembly-CSharp.dll</HintPath>
    </Reference>
    <Reference Include="GameTemplateAssembly">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\Sable\BepInEx\interop\GameTemplateAssembly.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Common">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\Sable\BepInEx\core\Il2CppInterop.Common.dll</HintPath>
    </Reference>
    <Reference Include="Il2CppInterop.Runtime">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\Sable\BepInEx\core\Il2CppInterop.Runtime.dll</HintPath>
    </Reference>
    <Reference Include="Il2Cppmscorlib">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\Sable\BepInEx\interop\Il2Cppmscorlib.dll</HintPath>
    </Reference>
    <Reference Include="Opencoding.Console">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\Sable\BepInEx\interop\Opencoding.Console.dll</HintPath>
    </Reference>
    <Reference Include="Unity.Addressables">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\Sable\BepInEx\interop\Unity.Addressables.dll</HintPath>
    </Reference>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>..\..\..\SteamLibrary\steamapps\common\Sable\BepInEx\interop\UnityEngine.CoreModule.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
