using System;
using System.Collections.Generic;
using UnityEngine;

namespace com.thegamefire.sablearchipelago;

public static class UtilityMappings
{
    public static Dictionary<String, String> LoadChumDictionary()
    {
        return new Dictionary<string, string>()
            {
                {"-3970;384;-3986", "Chum 1"},
                {"-3939;81;3076", "Chum 2"},
                {"-3847;256;-3712", "Chum 3"},
                {"-3782;73;-2287", "Chum 4"},
                {"-3766;57;2353", "Chum 5"},
                {"-3757;35;-2180", "Chum 6"},
                {"-3720;-29;2427", "Chum 7"},
                {"-3705;68;2399", "Chum 8"},
                {"-3692;27;2398", "Chum 9"},
                {"-3691;24;2315", "Chum 10"},
                {"-3688;93;-2355", "Chum 11"},
                {"-3604;47;-2302", "Chum 12"},
                {"-3526;33;4210", "Chum 13"},
                {"-3485;44;4182", "Chum 14"},
                {"-3410;92;643", "Chum 15"},
                {"-3402;45;4176", "Chum 16"},
                {"-3367;104;626", "Chum 17"},
                {"-3361;18;2925", "Chum 18"},
                {"-3355;71;619", "Chum 19"},
                {"-3341;54;1032", "Chum 20"},
                {"-3314;70;431", "Chum 21"},
                {"-3307;70;674", "Chum 22"},
                {"-3288;16;2938", "Chum 23"},
                {"-3265;100;599", "Chum 24"},
                {"-3250;89;511", "Chum 25"},
                {"-3238;15;2979", "Chum 26"},
                {"-3230;22;2655", "Chum 27"},
                {"-3201;5;2811", "Chum 28"},
                {"-3196;43;3627", "Chum 29"},
                {"-3186;26;2823", "Chum 30"},
                {"-3183;79;593", "Chum 31"},
                {"-3180;71;390", "Chum 32"},
                {"-3169;118;535", "Chum 33"},
                {"-3166;54;499", "Chum 34"},
                {"-3158;51;2749", "Chum 35"},
                {"-3145;207;-894", "Chum 36"},
                {"-3130;57;690", "Chum 37"},
                {"-3130;29;2934", "Chum 38"},
                {"-3128;71;1948", "Chum 39"},
                {"-3100;118;723", "Chum 40"},
                {"-2976;88;-849", "Chum 41"},
                {"-2967;47;730", "Chum 42"},
                {"-2959;150;-764", "Chum 43"},
                {"-2856;134;-2645", "Chum 44"},
                {"-2700;72;645", "Chum 45"},
                {"-2391;163;-2105", "Chum 46"},
                {"-2322;194;-2137", "Chum 47"},
                {"-2317;194;-2098", "Chum 48"},
                {"-2281;163;-2074", "Chum 49"},
                {"-1989;153;-268", "Chum 50"},
                {"-1965;125;-220", "Chum 51"},
                {"-1936;134;-265", "Chum 52"},
                {"-1911;186;2714", "Chum 53"},
                {"-1880;83;-267", "Chum 54"},
                {"-1864;64;2707", "Chum 55"},
                {"-1837;129;2622", "Chum 56"},
                {"-1826;143;-2193", "Chum 57"},
                {"-1808;91;2709", "Chum 58"},
                {"-1752;117;-2193", "Chum 59"},
                {"-1702;202;-108", "Chum 60"},
                {"-1697;155;-138", "Chum 61"},
                {"-1641;108;-2197", "Chum 62"},
                {"-1540;53;1727", "Chum 63"},
                {"-1532;58;1776", "Chum 64"},
                {"-1495;48;1777", "Chum 65"},
                {"-1485;83;1768", "Chum 66"},
                {"-1293;46;-3898", "Chum 67"},
                {"-1186;72;2992", "Chum 68"},
                {"-1177;111;-3785", "Chum 69"},
                {"-1133;30;-3829", "Chum 70"},
                {"-1058;52;2788", "Chum 71"},
                {"-930;103;2546", "Chum 72"},
                {"-413;265;-1183", "Chum 73"},
                {"-238;278;-1166", "Chum 74"},
                {"-146;102;-1759", "Chum 75"},
                {"-12;53;811", "Chum 76"},
                {"-4;116;821", "Chum 77"},
                {"27;72;779", "Chum 78"},
                {"201;40;-2529", "Chum 79"},
                {"228;25;846", "Chum 80"},
                {"268;38;-2336", "Chum 81"},
                {"297;18;-2447", "Chum 82"},
                {"297;13;-1676", "Chum 83"},
                {"322;103;-1654", "Chum 84"},
                {"345;38;-2395", "Chum 85"},
                {"351;188;-1644", "Chum 86"},
                {"353;111;-1630", "Chum 87"},
                {"373;103;-1795", "Chum 88"},
                {"540;150;-1125", "Chum 89"},
                {"565;40;-1123", "Chum 90"},
                {"864;84;2155", "Chum 91"},
                {"870;48;2096", "Chum 92"},
                {"882;69;2068", "Chum 93"},
                {"1104;133;-3977", "Chum 94"},
                {"1160;17;-772", "Chum 95"},
                {"1229;37;-791", "Chum 96"},
                {"1229;58;-751", "Chum 97"},
                {"1327;41;-626", "Chum 98"},
                {"1378;68;-3246", "Chum 99"},
                {"1393;100;-3483", "Chum 100"},
                {"1469;93;-3353", "Chum 101"},
                {"1501;62;-477", "Chum 102"},
                {"1524;108;-3449", "Chum 103"},
                {"1565;25;2332", "Chum 104"},
                {"1621;64;792", "Chum 105"},
                {"1633;71;729", "Chum 106"},
                {"1647;27;2399", "Chum 107"},
                {"1658;58;836", "Chum 108"},
                {"1685;102;846", "Chum 109"},
                {"1691;33;2333", "Chum 110"},
                {"1710;48;2217", "Chum 111"},
                {"1781;89;2477", "Chum 112"},
                {"1981;2;4640", "Chum 113"},
                {"2105;17;4657", "Chum 114"},
                {"2221;15;4323", "Chum 115"},
                {"2307;179;-3248", "Chum 116"},
                {"2316;6;4642", "Chum 117"},
                {"2364;229;-3269", "Chum 118"},
                {"2390;126;-3289", "Chum 119"},
                {"2690;20;755", "Chum 120"},
                {"2796;77;-2364", "Chum 121"},
                {"2811;43;3768", "Chum 122"},
                {"2828;13;3854", "Chum 123"},
                {"2831;97;-2357", "Chum 124"},
                {"2854;33;971", "Chum 125"},
                {"2878;216;-2355", "Chum 126"},
                {"2903;2;3942", "Chum 127"},
                {"2958;143;-3245", "Chum 128"},
                {"3036;7;3922", "Chum 129"},
                {"3102;62;235", "Chum 130"},
                {"3109;26;331", "Chum 131"},
                {"3128;20;1125", "Chum 132"},
                {"3143;47;456", "Chum 133"},
                {"3171;38;1135", "Chum 134"},
                {"3174;122;-394", "Chum 135"},
                {"3209;64;-340", "Chum 136"},
                {"3235;12;961", "Chum 137"},
                {"3236;105;-329", "Chum 138"},
                {"3249;111;-405", "Chum 139"},
                {"3345;138;-308", "Chum 140"},
                {"3392;79;409", "Chum 141"},
                {"3405;85;846", "Chum 142"},
                {"3427;98;266", "Chum 143"},
                {"3427;72;1039", "Chum 144"},
                {"3835;122;-1964", "Chum 145"},
                {"3835;31;4505", "Chum 146"},
                {"3849;154;-2195", "Chum 147"},
                {"3849;185;-2116", "Chum 148"},
                {"3866;164;-2113", "Chum 149"},
                {"3886;89;-2082", "Chum 150"},
                {"3894;109;-3445", "Chum 151"},
                {"3928;128;-3547", "Chum 152"},
                {"3951;93;-1762", "Chum 153"},
                {"3996;139;-3790", "Chum 154"},
                {"4124;136;-3632", "Chum 155"},
                {"4203;7;3332", "Chum 156"},
                {"4233;120;3396", "Chum 157"},
                {"4235;64;2614", "Chum 158"},
                {"4240;78;3396", "Chum 159"},
                {"4258;12;3307", "Chum 160"},
                {"4262;26;3245", "Chum 161"},
                {"4263;171;-2868", "Chum 162"},
                {"4284;66;3238", "Chum 163"},
                {"4454;78;-809", "Chum 164"},
                {"4484;88;-929", "Chum 165"},
            };
    }

    public static HashSet<string> NonRandomizedItems()
    {
        return new HashSet<string>()
        {
            "ChildhoodSetMask",
            "ChildhoodSetTop",
            "ChildhoodSetTrousers",
            "Calibrator",
            "ControlPanel",
            "PowerSupply",
            "Compass",
            "GlidingStone01",
            "GlidingStone02",
            "Navigator",
            "CatEarCanyonMap",
            
            
            "AtomicSuitHelmet",
            "CartographersMask",
            "ChumMask",
            "ClimbingSetMask",
            "EngineerSetHelmet",
            "EntertainersMask",
            "FishingSetMask",
            "GuardMask",
            "HerculesBeetleMask",
            "IbexiiSetMask",
            "MerchantsMask",
            "SandwormMask",
            "ScrappersMask",
            "ShadeOfEccriaMask",
        };
    }

    public static Dictionary<string, string> LoadServerItemNameDict()
    {
        return new Dictionary<string, string>()
            {
                {"Hicaric Ring Artefact", "AnAncientRaceKeyItem"},
                {"Angler Badge", "AnglerBadge"},
                {"Angler Bike Engine", "AnglerBikeBooster"},
                {"Angler Bike Front", "AnglerBikeFront"},
                {"Angler Bike Wings", "AnglerBikeWings"},
                {"Atomic Core Dye", "AtomicCorePalette"},
                {"Atomic Heart Keycard", "AtomicHeartKeycard"},
                {"Broken Atomic Heart Powercore", "AtomicHeartPowerCoreBroken"},
                {"Repaired Atomic Heart Powercore", "AtomicHeartPowerCoreRepaired"},
                {"CLUE: Promissory Note", "AtomicHeartDebtNote"},
                {"CLUE: Empty Socket", "AtomicHeartEmptySocket"},
                {"CLUE: Large Feathers", "AtomicHeartFeather"},
                {"CLUE: Smashed Glass", "AtomicHeartSmashedGlass"},
                {"SUSPECT: Climber Garay", "AtomicHeartSuspectGaray"},
                {"SUSPECT: Machinist Hamza", "AtomicHeartSuspectHamza"},
                {"SUSPECT: Merchant Iria", "AtomicHeartSuspectIria"},
                {"Atomic Priesthood Mask", "AtomicPriesthoodSetMask"},
                {"Atomic Priesthood Torso", "AtomicPriesthoodSetTop"},
                {"Atomic Priesthood Trousers", "AtomicPriesthoodSetTrousers"},
                {"Atomic Shell Dye", "AtomicShellPalette"},
                {"Whale Ship Mask", "AtomicSuitHelmet"},
                {"Whale Ship Top", "AtomicSuitTop"},
                {"Whale Ship Trousers", "AtomicSuitTrousers"},
                {"Whale Ship Bike Engine", "AtomicWhaleshipBikeBooster"},
                {"Whale Ship Bike Front", "AtomicWhaleshipBikeFront"},
                {"Whaleship Bike Dye", "AtomicWhaleShipBikePalette"},
                {"Whale Ship Bike Wing", "AtomicWhaleshipBikeWings"},
                {"Azure Dye", "AzurePalette"},
                {"Badlands Map", "BadlandsMap"},
                {"Basic Wooden Rod", "BasicFishingRod"},
                {"Beetle Badge", "BeetleBadge"},
                {"Beetle Bike Dye", "BeetleBikePalette"},
                {"Beetle Bike Booster", "BeetleBooster"},
                {"Beetle Bike Front", "BeetleFront"},
                {"Beetle Husk Dye", "BeetleHuskPalette"},
                {"Beetle Station Top", "BeetleSetTop"},
                {"Beetle Station Trousers", "BeetleSetTrousers"},
                {"Beetle Bike Wings", "BeetleWings"},
                {"Bellow Guppy", "BellowGuppy"},
                {"Bellow Guppy Clue", "BellowGuppyClue"},
                {"Biker Top", "BikerSetTop"},
                {"Bikers Trousers", "BikerSetTrousers"},
                {"Hakoa Map", "BlackDesertMap"},
                {"Hakoan Top", "BlackDesertSetTop"},
                {"Hakoan Trousers", "BlackDesertSetTrousers"},
                {"Bloated Eye Clam", "BloatedEyeClam"},
                {"Bloated Eye Clam Clue", "BloatedEyeClamClue"},
                {"Cactus Spine Rod", "CactusSpineRod"},
                {"Atomic Calibrator", "Calibrator"},
                {"Cartographer Bike Engine", "CartoBikeBooster"},
                {"Cartographer Bike Front", "CartoBikeFront"},
                {"Cartographer Bike Wings", "CartoBikeWings"},
                {"Cartographer Bike Dye", "CartographerPalette"},
                {"Cartographer's Badge", "CartographersBadge"},
                {"Cartographer's Mask", "CartographersMask"},
                {"Ewer Map", "CatEarCanyonMap"},
                {"Chalk Butterfly", "ChalkButterfly"},
                {"Child's Mask", "ChildhoodSetMask"},
                {"Ibexii Children Top", "ChildhoodSetTop"},
                {"Ibexii Trousers", "ChildhoodSetTrousers"},
                {"Chum Egg", "Chum"},
                {"Chum Skirt", "ChumBottoms"},
                {"Chum Mask", "ChumMask"},
                {"Chum Queen Tear", "ChumTear"},
                {"Chum Top", "ChumTop"},
                {"Climbing Badge", "ClimbingBadge"},
                {"Bouldering Trousers", "ClimbingSetBottoms"},
                {"Climbing Mask", "ClimbingSetMask"},
                {"Bouldering Top", "ClimbingSetTop"},
                {"The Compass", "Compass"},
                {"Atomic Control Panel", "ControlPanel"},
                {"Crazy Bike Dye", "CrazyBikePalette"},
                {"Crystal Butterfly", "CrystalButterfly"},
                {"Delivery Bike Engine", "DeliveryBikeBooster"},
                {"Delivery Bike Front", "DeliveryBikeFront"},
                {"Delivery Bike Dye", "DeliveryBikePalette"},
                {"Delivery Bike Wings", "DeliveryBikeWings"},
                {"Dopey Dart", "DopeyDart"},
                {"Dopey Dart Clue", "DopeyDartClue"},
                {"Dragonfly Bike Engine", "DragonflyBikeBooster"},
                {"Dragonfly Bike Front", "DragonflyBikeFront"},
                {"Dragonfly Bike Wings", "DragonflyBikeWings"},
                {"Dragonfly Bike Dye", "DragonFlyPalette"},
                {"Butterfly Top", "DragonFlySetTop"},
                {"Butterfly Trousers", "DragonFlySetTrousers"},
                {"Dusk Firefly", "DuskFirefly"},
                {"Dusty Monument Dye", "DustyMonumentPalette"},
                {"Sansee Map", "EasternDuneMap"},
                {"Eccrine Top", "EccrianSetTop"},
                {"Eccrine Trousers", "EccrianSetTrousers"},
                {"Eccrine Green Dye", "EccrineGreenPalette"},
                {"Machinist's Mask", "EngineerSetHelmet"},
                {"Machinist Top", "EngineerSetTop"},
                {"Machinist Trousers", "EngineerSetTrousers"},
                {"Entertainer's Badge", "EntertainersBadge"},
                {"Entertainer's Mask", "EntertainersMask"},
                {"Salt Extractor Bike Dye", "ExtractorPalette"},
                {"Eyries Bike Booster", "EyriesBikeBooster"},
                {"Eyries Bike Front", "EyriesBikeFront"},
                {"Eyries Bike Dye", "EyriesBikePalette"},
                {"Eyries Bike Wings", "EyriesBikeWings"},
                {"Fallow Pomegranate ", "FallowPomegranate"},
                {"Narrow Stalk Fig", "Fig"},
                {"Eyries Top", "FingerClanSetTop"},
                {"Eyries Trousers", "FingerClanSetTrousers"},
                {"Angler Mask", "FishingSetMask"},
                {"Angler Top", "FishingSetTop"},
                {"Angler Bottoms", "FishingSetTrousers"},
                {"Flutter Thrust", "FlutterThrust"},
                {"Flutter Thrust Clue", "FlutterThrustClue"},
                {"Ghost Soul", "GhostSoul"},
                {"Ghost Soul Clue", "GhostSoulClue"},
                {"Giraffe Bike Dye", "GiraffeBikePalette"},
                {"Giraffe Bike Booster", "GiraffeBooster"},
                {"Giraffe Bike Front", "GiraffeFront"},
                {"Giraffe Bike Wings", "GiraffeWings"},
                {"Gliding Bike Booster", "GlidingBikeBooster"},
                {"Gliding Bike Front", "GlidingBikeFront"},
                {"Gliding Bike Dye", "GlidingBikePalette"},
                {"Gliding Bike Wings", "GlidingBikeWings"},
                {"Gliding Stone", "GlidingStone01"},
                {"Powered Gliding Stone", "GlidingStone02"},
                {"Glowing Mushrooms", "GlowingMushrooms"},
                {"Hakoan Glowworms", "Glowworm"},
                {"Guard's Mask", "GuardMask"},
                {"Eccrine Guard Trousers", "GuardOutfitBottoms"},
                {"Eccrine Guard Top", "GuardOutfitTop"},
                {"Guard's Badge", "GuardsBadge"},
                {"Hakoan Black Dye", "HakoanBlackPalette"},
                {"Hercules Beetle Mask", "HerculesBeetleMask"},
                {"Hummer", "Hummer"},
                {"Hummer Clue", "HummerClue"},
                {"Hunters Mask", "HuntersMask"},
                {"Ibexii Red Dye", "IbexiiRedPalette"},
                {"Ibexii Mask", "IbexiiSetMask"},
                {"Ibexii Glider Top", "IbexiiSetTop"},
                {"Ibexii Glider Trousers", "IbexiiSetTrousers"},
                {"Hercules Beetle Larvae Husk", "LarvalHusk"},
                {"Larval Husk Package", "LarvalHuskPackage"},
                {"Lavender Flash Dye", "LavenderFlashPalette"},
                {"Light Koi", "LightKoi"},
                {"Light Koi Clue", "LightKoiClue"},
                {"Lightning Crystal", "LightningCrystal"},
                {"Lightning Crystal Bike Booster", "LightningCrystalBikeBooster"},
                {"Lightning Crystal Bike Front", "LightningCrystalBikeFront"},
                {"Lightning Crystal Bike Dye", "LightningCrystalBikePalette"},
                {"Lightning Crystal Bike Wings", "LightningCrystalBikeWings"},
                {"Little Kicker", "LittleKicker"},
                {"Little Kicker Clue", "LittleKickerClue"},
                {"Machinist Badge", "MachinistBadge"},
                {"Melancholy Mushroom", "MelancholyMushroom"},
                {"Merchant Badge", "MerchantBadge"},
                {"Merchant's Mask", "MerchantsMask"},
                {"Hicaric Bike Booster Schematic", "MonumentalBikeBoosterSchematic"},
                {"Hicaric Bike Front Schematic", "MonumentalBikeFrontSchematic"},
                {"Monumental Bike Dye", "MonumentalBikePalette"},
                {"Hicaric Bike Wings Schematic", "MonumentalBikeWingsSchematic"},
                {"Monumental Stone Bottoms", "MonumentalBottom"},
                {"Hicaric Ring Bike Booster", "MonumentalRingBikeBooster"},
                {"Hicaric Ring Bike Front", "MonumentalRingBikeFront"},
                {"Hicaric Ring Bike Wings", "MonumentalRingBikeWings"},
                {"Monumental Stone Top", "MonumentalTop"},
                {"Natures Green Dye", "NaturesGreenPalette"},
                {"The Navigator", "Navigator"},
                {"Neon Flash Dye", "NeonFlashPalette"},
                {"Nimoor Butterflies", "NimoorButterflies"},
                {"Nomadic Bike Dye", "NomadicBikePalette"},
                {"Nomadic Bike Engine", "NomadicBooster"},
                {"Nomadic Bike Front", "NomadicFront"},
                {"Nomadic Bike Wing", "NomadicWings"},
                {"Oasis Dragonfly", "OasisDragonfly"},
                {"Oasis Flower", "OasisFlower"},
                {"Orange Winged Beetles", "OrangeWingBeetle"},
                {"Oranged Ringed Beetle Mask", "ParasiteBeetleMask"},
                {"Pebble Eye", "PebbleEye"},
                {"Pebble Eye Clue", "PebbleEyeClue"},
                {"Pill Fish", "PillFish"},
                {"Pill Fish Clue", "PillFishClue"},
                {"Pink Neck Eggs", "PinkNeckEggs"},
                {"Atomic Power Supply", "PowerSupply"},
                {"Prickly Pear", "PricklyPear"},
                {"Pyrausta Grey Dye", "PyraustaGreyPalette"},
                {"Red Bike Dye", "RedBikePalette"},
                {"Sable Hunch Trousers", "SableHunchTrousers"},
                {"Salt Bike Engine", "SaltBikeBooster"},
                {"Salt Bike Front", "SaltBikeFront"},
                {"Salt Bike Wings", "SaltBikeWings"},
                {"Salt Butterfly", "SaltButterfly"},
                {"Salt Plain Pools Dye", "SaltPlainPoolsPalette"},
                {"Sodic Waste Map", "SaltPlainsMap"},
                {"Sandcutter Bike Dye", "SandcutterBikePalette"},
                {"Sandcutter Engine", "SandcutterBooster"},
                {"Sandcutter Front", "SandcutterFront"},
                {"Sandcutter Wings", "SandcutterWings"},
                {"Sand Ray", "SandRay"},
                {"Sand Ray Clue", "SandRayClue"},
                {"Sandwyrm Mask", "SandwormMask"},
                {"Sandy Dye", "SandyPalette"},
                {"Scabby Fish", "ScabbyFish"},
                {"Scabby Fish Clue", "ScabbyFishClue"},
                {"Scrap Metal", "ScrapMetal"},
                {"Scrapper Bike Engine", "ScrapperBikeBooster"},
                {"Scrapper Bike Front", "ScrapperBikeFront"},
                {"Scrapper Bike Wings", "ScrapperBikeWings"},
                {"Scrapper Bike Dye", "ScrapperPalette"},
                {"Scrapper's Badge", "ScrappersBadge"},
                {"Scrapper Top", "ScrapperSetTop"},
                {"Scrapper Bottoms", "ScrapperSetTrousers"},
                {"Scrapper Mask", "ScrappersMask"},
                {"Shaded Leaf Butterfly", "ShadedLeafButterfly"},
                {"Shade Bike Booster", "ShadeOfEccriaBooster"},
                {"Shade Bike Front", "ShadeOfEccriaFront"},
                {"Shade of Eccria Mask", "ShadeOfEccriaMask"},
                {"Shade Bike Wings", "ShadeOfEccriaWings"},
                {"Shade Top", "ShadeSetTop"},
                {"Shade Trousers", "ShadeSetTrousers"},
                {"Shelled Cup", "ShelledCup"},
                {"Shelled Cup Clue", "ShelledCupClue"},
                {"Shepherd Mask", "ShepherdsMask"},
                {"Shy Rijwur Pulp", "ShyRijwurPulp"},
                {"Slicer Beetle Mask", "SlicerBeetleMask"},
                {"Slicer Beetle Poo", "SlicerBeetlePoo"},
                {"Speedster Bike Engine", "SpeedsterBikeBooster"},
                {"Speedster Bike Front", "SpeedsterBikeFront"},
                {"Speedster Bike Dye", "SpeedsterBikePalette"},
                {"Speedster Bike Wing", "SpeedsterBikeWings"},
                {"Stepwell Dragonfly", "StepwellDragonfly"},
                {"Storm Fish", "StormFish"},
                {"Storm Fish Clue", "StormFishClue"},
                {"Straw Dye", "StrawPalette"},
                {"Mysterious Note", "StyllousNote"},
                {"Sucker Fish", "SuckerFish"},
                {"Sucker Fish Clue", "SuckerFishClue"},
                {"Sunsets Dye", "SunsetsPalette"},
                {"Sunshine Butterfly", "SunshineButterfly"},
                {"Sand Surfer Top", "SurferSetTop"},
                {"Sand Surfer Shorts", "SurferSetTrousers"},
                {"Teacup Angler", "TeacupAngler"},
                {"Teacup Angler Clue", "TeacupAnglerClue"},
                {"Magpie Key", "ThievingMagpiesWellDoorKey"},
                {"Trickster Atomic Rod", "TricksterAtomicRod"},
                {"Trifle Jelly", "TrifleJelly"},
                {"Trifle Jelly Clue", "TrifleJellyClue"},
                {"Wash Blue Dye", "WashBluePalette"},
                {"Redsee Map", "WesternDuneMap"},
                {"The Wash Map", "WhiteDesertMap"},
                {"Wash Top", "WhiteDesertSetTop"},
                {"Wash Trousers", "WhiteDesertSetTrousers"},
                {"Wind Chime Dye", "WindChimePalette"},
                {"Yellow Elephant Beetle", "YellowElephantBeetle"},
            };
    }

    public static Dictionary<Vector3, string> GetHicaricRingLocations()
    {
        return new Dictionary<Vector3, string>()
        {
            {new Vector3(1780, 30, 2465), "Hicaric Ring (Sansee)"},
            {new Vector3(-3116, 12, 1945), "Hicaric Ring (Redsee)"},
            {new Vector3(4235, 6, 2602), "Hicaric Ring (Sodic Waste)"},
            {new Vector3(-137, 43, -1750), "Hicaric Ring (Badlands)"},
            {new Vector3(-2845, 75, -2650), "Hicaric Ring (Hakoa)"},
            {new Vector3(4254, 111, -2876), "Hicaric Ring (The Wash)"}
        };
    }
}